employees ui update
entropy-code/entropay-admin-ui pull request #11
Opened 2022-10-24 15:23 UTC by FacuOrellana

Employees UI update

2022-10-26 14:55 UTC, agustinb4 requested changes
Some minor changes in the style

2022-10-26 14:55 UTC, agustinb4 commented on src/employees.js
> +import { DateInput, Edit, SimpleForm, TextInput, Create, SelectInput, ReferenceInput,SelectArrayInput,ChipField,ReferenceArrayInput } from 'react-admin';
Please format this line

2022-10-26 14:55 UTC, agustinb4 commented on src/employees.js
> +        <TextInput source="internalId" />
Check the format here

2022-10-26 14:55 UTC, agustinb4 commented on src/employees.js
>  );
Add a new line at the end of the file here

2022-10-27 15:20 UTC, agustinb4 approved these changes

2022-10-30 14:12 UTC, reconeazaretzky approved these changes

2022-11-08 13:52 UTC, merged