EN-7
entropy-code/entropay-admin-ui pull request #20
Opened 2022-12-21 16:02 UTC by marcosihe

-Refactor forms into CreateForm and EditForm
-Modify views: clients, employees, contracts, company, project, projectTypes, roles, and seniorities, in order to be able to use CreateForm.jsx and EditForm.jsx
-Refactor the data contained in the forms, creating the const formData.

2022-12-21 18:38 UTC, agustinb4 requested changes
Good job man!

2022-12-21 18:38 UTC, agustinb4 commented on src/projectTypes.js
> +    inputsList: [{ name: "name" }],
Same here:  `inputsList: [{ name: "name", type:"string" }],`

2022-12-21 18:41 UTC, marcosihe commented on src/roles.js
> +    inputsList: [{ name: "name" }],
you're right! thanks for noticing that!

2022-12-21 18:50 UTC, marcosihe commented on src/projectTypes.js
> +    inputsList: [{ name: "name" }],
Done

2022-12-21 18:50 UTC, marcosihe commented on src/roles.js
> +    inputsList: [{ name: "name" }],
Done

2022-12-21 18:51 UTC, marcosihe commented on src/contracts.js
> +      reference: "companies",
Done, nice catch!

2022-12-21 18:51 UTC, marcosihe commented on src/components/forms/CreateForm.jsx
> +      <Create>
Done!

2022-12-22 12:57 UTC, agustinb4 commented on src/contracts.js
> +      multiselect: true,
should be false

2022-12-22 12:57 UTC, agustinb4 commented on src/contracts.js
> +      optionText: "name",
should be lastName

2022-12-22 12:58 UTC, agustinb4 commented on src/contracts.js
> +    paymentInformation: false,
please remove from all component on false cases  (if no necessary)

2022-12-22 14:25 UTC, marcosihe commented on src/contracts.js
> +    paymentInformation: false,
Done

2022-12-22 14:25 UTC, marcosihe commented on src/contracts.js
> +      optionText: "name",
Done

2022-12-22 14:26 UTC, marcosihe commented on src/contracts.js
> +      multiselect: true,
Done

2022-12-22 14:28 UTC, agustinb4 approved these changes
:rocket:

2022-12-22 14:29 UTC, merged