[EN-74] Show salary in Contract view
entropy-code/entropay-admin-ui pull request #61
Opened 2023-04-08 11:48 UTC by baremarco

# Description :pencil:

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Created CustomizableChipField component to render custom content using a function passed as a child.
- Added HasPermission to control visibility of the content (Salary information)
## Link to ticket :link:

https://entropyteam.atlassian.net/browse/EN-74

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? :microscope:

- Was created different types of _Payment settlement_ between the different currency types
-  Was created different types of _Payment settlement_ between the different modality types
- Was created different types of _Payment settlement_ up to three to test the component's arrange for the available space

2023-04-10 14:50 UTC, agustinb4 requested changes

2023-04-10 14:50 UTC, agustinb4 commented on src/contracts.js
> +      {HasPermissions("contracts", "read") && (
You could remove this check, we are checking the permissions at resource level

2023-04-10 14:50 UTC, agustinb4 commented on src/contracts.js
> +                  return label;
For Developer and Analyst role (they cannot see salary), i saw the value of ${record.salary} is null, so i think we could improve this with something like:
```
if (record) {
  const salary = `${record.salary}` === "null" ? '-' : `${record.salary}`
  return `${record.currency} ${salary} /${record.modality.charAt(0).toLowerCase()}`;
}
```

2023-04-12 16:26 UTC, agustinb4 approved these changes
Looks good!

2023-04-12 16:32 UTC, FacuOrellana approved these changes
nice

2023-04-14 13:51 UTC, merged