EN-76: Prefill new contract/assignment with active information
entropy-code/entropay-admin-ui pull request #65
Opened 2023-04-20 13:30 UTC by FacuOrellana

# Description :pencil:

When a new contract/employee is created from employees profile, the latest active information is prefill in the form.

## Link to ticket :link:

https://entropyteam.atlassian.net/browse/EN-76

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? :microscope:

Manual testing
New contract prefill with information from active contract
![image](https://user-images.githubusercontent.com/70980835/233380641-b8c5ea45-9bdc-4889-aec7-d20e734c573b.png)

New contract prefill from employee without active contract
![image](https://user-images.githubusercontent.com/70980835/233381115-670e1b49-a4ac-4a0e-864e-94d902211246.png)

New assignment prefill with information from latest employee assignment
![image](https://user-images.githubusercontent.com/70980835/233381704-2237fd94-81ac-43b9-8015-faa452ecf79d.png)

New assignment from employee without assignment
![image](https://user-images.githubusercontent.com/70980835/233381357-963a7cbc-2d62-48b7-b898-0d908056032a.png)

2023-04-21 13:24 UTC, agustinb4 requested changes

2023-04-21 14:15 UTC, FacuOrellana commented on src/employeeProfiles.js
> +  return data !== undefined ? data.find((a) => a.endDate === null) : null;
in that case, witch assignment we should consider as lastest?

2023-04-21 14:46 UTC, agustinb4 commented on src/employeeProfiles.js
> +  return data !== undefined ? data.find((a) => a.endDate === null) : null;
I guess we could filter for the assignment with the last start dale. 
Also we have to contemplate the case when we have 2 active assignment. so it should work
what do you think?

2023-04-21 14:51 UTC, FacuOrellana commented on src/employeeProfiles.js
> +  return data !== undefined ? data.find((a) => a.endDate === null) : null;
it should work, we have to keep the same rule to display the current assignment in employee card. Until we add active field in assignment we should use the same criteria in both places.

2023-04-21 14:57 UTC, agustinb4 commented on src/employeeProfiles.js
> +  return data !== undefined ? data.find((a) => a.endDate === null) : null;
you're right. for that case i used the last end date when all the assignments has end date. 
what's about add the last assignment to the employee dto, then use this data to populate de assignments fields?

2023-04-21 15:04 UTC, FacuOrellana commented on src/employeeProfiles.js
> +  return data !== undefined ? data.find((a) => a.endDate === null) : null;
sounds like a great solution to me

2023-04-25 21:12 UTC, baremarco approved these changes

2023-04-26 14:23 UTC, agustinb4 approved these changes

2023-04-26 14:49 UTC, merged