EN-78: Add holidays per location
entropy-code/entropay-admin-ui pull request #71
Opened 2023-05-16 16:43 UTC by FacuOrellana

# Description :pencil:

As admin role, now holidays and countries can be add to build a holiday calendar per location. Holidays list can be filtered by country and year option.

## Link to ticket :link:

https://entropyteam.atlassian.net/browse/EN-78

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? :microscope:

New layouts

![image](https://github.com/entropy-code/entropay-admin-ui/assets/70980835/d0602db7-1028-4635-a101-b2973b5bd5ad)

![image](https://github.com/entropy-code/entropay-admin-ui/assets/70980835/4e7ccd7d-0b6e-47e2-8557-222d088bc054)

![image](https://github.com/entropy-code/entropay-admin-ui/assets/70980835/410980be-6288-4ff5-a6ef-3273a7bdd5bd)

2023-06-01 19:58 UTC, baremarco approved these changes

2023-06-02 18:33 UTC, agustinb4 requested changes

2023-06-02 18:33 UTC, agustinb4 commented on src/types/holidays.tsx
> +  localStorage.removeItem("RaStore.holidays.listParams"); // move
please remove this

2023-06-07 15:46 UTC, agustinb4 approved these changes

2023-06-07 15:55 UTC, merged