EN-81: See next time off of my employees
entropy-code/entropay-admin-ui pull request #90
Opened 2023-07-21 15:05 UTC by FacuOrellana

# Description :pencil:

# Description :pencil:
Now we can easily see the next time off for employees, it was added to the cards.

## Link to ticket :link:

https://entropyteam.atlassian.net/browse/EN-81

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? :microscope:

Employee cards
![image](https://github.com/entropy-code/entropay-admin-ui/assets/70980835/1775bf14-e7fe-4574-9b0d-fb0ac59b48d9)

Employee list
![image](https://github.com/entropy-code/entropay-admin-ui/assets/70980835/b7e1cc17-028e-42b1-a299-e06afd7f33e1)

2023-07-24 12:51 UTC, FedericoA15 approved these changes
nice work!

2023-07-25 14:28 UTC, agustinb4 requested changes

2023-07-25 14:28 UTC, agustinb4 commented on src/employees.js
> +  { name: "nearestPto", type: "text" },
it should be type: "date"

2023-07-25 14:28 UTC, agustinb4 commented on src/employees.js
> +                        {record.nearestPto && (
please use: `<DateField source="nearestPto" locales={locale} />`

2023-07-25 16:06 UTC, agustinb4 approved these changes

2023-07-25 16:07 UTC, merged